name: CI
on:
  push:
    tags: [ 'v*' ]
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v3
      - uses: bleep-build/bleep-setup-action@0.0.1
      - uses: coursier/cache-action@v6
        with:
          extraFiles: bleep.yaml
      - name: Compile
        run: bleep compile

  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [ build ]
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - uses: actions/checkout@v3
      - uses: bleep-build/bleep-setup-action@0.0.1
      - name: Release
        run: bleep publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
